### ISSUE TITLE
Xubuntu 18.04LTS

### ISSUE THREAD

**Issue by mhdbabiker** [tkeskita/BVtkNodes#13]
I found the following error during adding VTK to blender

Traceback (most recent call last):
  File "/home/mohammed/Post-Processing/Blender/blender-2.83.0-linux64/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/mohammed/.config/blender/2.83/scripts/addons/BVtkNodes-master/__init__.py", line 114, in <module>
    from . import core
  File "/home/mohammed/.config/blender/2.83/scripts/addons/BVtkNodes-master/core.py", line 26, in <module>
    from .update import *
  File "/home/mohammed/.config/blender/2.83/scripts/addons/BVtkNodes-master/update.py", line 193, in <module>
    open(logfile, 'w').write('')
PermissionError: [Errno 13] Permission denied: '/home/mohammed/.config/blender/2.83/scripts/addons/BVtkNodes-master/vtklog.txt'

**Comment by tkeskita** [comment]
Looks like you don't have write permission to add-on folder, where add-on is trying to create vtklog.txt. Are you running Blender as normal user?

**Comment by mhdbabiker** [comment]
Yes, I am. i have the folder blender-2.83-linux64 and i open the terminal inside the folder and run it using ./blender

**Comment by tkeskita** [comment]
Maybe this is ownership or writability issue. Please check file ownership and make writable file `~/.config/blender/2.83/scripts/addons/BVtkNodes-master/vtklog.txt` and `BVtkNodes-master` directory. If they have correct rights, you can edit and save `vtklog.txt` at that directory in a text editor. Does that work?
