### ISSUE TITLE
error when vtkUnstructuredGridReader update .vtk data

### ISSUE THREAD

**Issue by HakunanMatatat** [tkeskita/BVtkNodes#98]
Error: Python: Traceback (most recent call last):
  File "C:\Users\chang\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BVtkNodes-master\core.py", line 771, in execute
    node.update_vtk()
  File "C:\Users\chang\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BVtkNodes-master\core.py", line 753, in update_vtk
    self.notify_downstream(vtk_status=new_status)
  File "C:\Users\chang\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BVtkNodes-master\core.py", line 689, in notify_downstream
    node.notify_downstream(vtk_status="out-of-date", origin_node=False)
  File "C:\Users\chang\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BVtkNodes-master\core.py", line 689, in notify_downstream
    node.notify_downstream(vtk_status="out-of-date", origin_node=False)
  File "C:\Users\chang\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BVtkNodes-master\core.py", line 689, in notify_downstream
    node.notify_downstream(vtk_status="out-of-date", origin_node=False)
  [Previous line repeated 4 more times]
AttributeError: 'Node' object has no attribute 'notify_downstream'

**Comment by tkeskita** [comment]
Hi, can you please share blend file or show a simple node tree and small example data which reproduced this? For .vtk data files you may need to use vtkPolyDataReader.
